# Configure dependabot to update the dependency for npm modules.

version: 2
updates:
  # Enable version updates for npm modules
  - package-ecosystem: 'npm'
    # Look for `package.json` and `package-lock.json` files in the `root` directory
    directory: '/'
    # Check the go registry for updates every day (weekdays)
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'cypress'
    reviewers:
      - 'dislbenn'
    open-pull-requests-limit: 5

  # Release 2.4
  - package-ecosystem: 'npm'
    target-branch: 'release-2.4'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'cypress'
    reviewers:
      - 'dislbenn'
    open-pull-requests-limit: 5

  # Release 2.3
  - package-ecosystem: 'npm'
    target-branch: 'release-2.3'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'cypress'
    reviewers:
      - 'dislbenn'
    open-pull-requests-limit: 5
