name: Update package dependencies versions

# Set jobs to be configured and executed by schedule.
on:
  workflow_dispatch:
    environment:
      description: Environment to run build against
      type: environment
  push:
    branches:
      - 'main'
      - 'release-2.3'
      - 'release-2.4'
  schedule:
    - cron: '0 6 * * 1-5' # Actions will be executed at 6am for every weekday.

# Set environment variables.
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node for repository code
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Node version should be 14.

      - name: Validate installed node version
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo "Using node version: $(node --version)"
          echo "Using npm version: $(npm -v)"

      - name: Install node modules package dependencies
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          npm install

      - name: Verify outdated node modules package dependencies versions
        continue-on-error: true # Continuing on error, we need to check for outdated modules, so it's okay for this step to fail.
        run: |
          echo "Preparing to list outdated node modules versions within current build"
          npm outdated

      - name: Update node modules package dependencies versions within package.json
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo "Preparing to update all outdated package modules to latest versions"
          npx npm-check-updates -u

      - name: Installing updated node modules package dependencies within the project
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo "Preparing to install the updated package dependencies"
          npm install

      - name: Resolve node modules package vulnerabilities
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo "Preparing to address security vulnerabilities in the updated package dependencies."
          npm audit fix

      - name: Create report to README
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        run: |
          echo -e "\nCreated automated PR: $(date +%S-%d-%m-%y)" >> README.md
          git status

      - name: Create pull request for updated node modules versions
        continue-on-error: true # Continuing on error, adding this for debugging purposes.
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: .
          body: >
            This PR is auto-generated by the Git action [search-e2e-test](https://github.com/stolostron/search-e2e-test/blob/main/.github/workflows/package-dependencies-update.yml).
          branch-suffix: short-commit-hash
          commit-message: 'Updated node module versions within the project'
          delete-branch: true
          signoff: true
          title: '[Automated PR] Updated node modules versions within the project'
          token: ${{ secrets.GITHUB_TOKEN }}
