name: Update package dependencies versions

# Set jobs to be configured and executed by schedule.
on:
  workflow_dispatch:
    environment:
      description: Environment to run build against
      type: environment
  push:
    branches:
      - 'main'
      - 'release-2.3'
      - 'release-2.4'
  schedule:
    - cron: '0 6 * * 1-5' # Actions will be executed at 6am for every weekday.

# Set environment variables.
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup node for repository code
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Node version should be 14.
          check-latest: true

      - name: Validate installed node version
        run: |
          echo "Using node version: $(node --version)"
          echo "Using npm version: $(npm -v)"

      - name: Install node modules package dependencies
        run: |
          npm install

      - name: Verify outdated node modules package dependencies versions
        continue-on-error: true # Continuing on error. The initial command will return an exit 1 code; however, this is okay.
        run: |
          echo "Preparing to list outdated node modules versions within current build"
          npm outdated

      - name: Update node modules package dependencies versions within package.json
        run: |
          mkdir -p .github/logs
          echo "Preparing to update all outdated package modules to latest versions"
          echo "Ignoring package update for cypress"
          npx npm-check-updates -u -x cypress >> .github/logs/update-log-$(date +%m-%d-%y).txt

      - name: Installing updated node modules package dependencies within the project
        run: |
          echo "Preparing to install the updated package dependencies"
          npm install

      - name: Resolve node modules package vulnerabilities
        continue-on-error: true # Continuing on error. This step is to avoid vulnerabilities; however, we incase it fails we will need to resolve them manually.
        run: |
          echo "Preparing to address security vulnerabilities in the updated package dependencies."
          npm audit fix

      - name: Add updated log report to README # Once the PR has been merged, the link will be active and available for view.
        run: |
          echo -e "\nGenerated auto rebuild. View log file created: [update-log-$(date +%m-%d-%y)](https://github.com/stolostron/search-e2e-test/blob/main/.github/logs/update-log-$(date +%m-%d-%y).txt)" >> README.md

      - name: Execute code linting # Executing this step incase the file format needs to be fixed.
        run: |
          npm run lint:fix
          git status

      - name: Create pull request for updated node modules versions
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: .
          body: |
            This PR is auto-generated by the Git action [package-dependencies-update](https://github.com/stolostron/search-e2e-test/blob/main/.github/workflows/package-dependencies-update.yml).
          branch-suffix: short-commit-hash
          commit-message: 'Updated node module versions within the project'
          delete-branch: true
          labels: automated-pr
          reviewers: dislbenn
          signoff: true
          title: '[Automated PR] Updated node modules versions within the project'
          token: ${{ secrets.GITHUB_TOKEN }}
